# Generated by Django 5.1.7 on 2025-03-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Car manufacturer', max_length=50)),
                ('model', models.CharField(help_text='Car model', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Year of manufacture')),
                ('color', models.CharField(blank=True, help_text='Car color', max_length=30, null=True)),
                ('license_plate', models.CharField(help_text='Unique license plate number', max_length=20)),
                ('seats', models.PositiveIntegerField(help_text='Total number of seats in the car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Starting location', max_length=100)),
                ('destination', models.CharField(help_text='Destination', max_length=100)),
                ('departure_time', models.DateTimeField(help_text='Departure date and time')),
                ('arrival_time', models.DateTimeField(blank=True, help_text='Estimated arrival time', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per seat', max_digits=6)),
                ('available_seats', models.PositiveIntegerField(help_text='Number of seats available for reservation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Trip creation timestamp')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='carpool.car')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_reserved', models.PositiveIntegerField(default=1, help_text='Number of seats reserved')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='Reservation status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Reservation creation timestamp')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.passengerprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='carpool.trip')),
            ],
        ),
    ]
